import { Head } from '@inertiajs/react';
import { PrintActions } from '@/components/print/print-actions';
import { useLocale } from '@/hooks/use-locale';

export default function CustomerLedgerPrint({ customer, organization, meta, pdfDownloadUrl, backHref }) {
  const { t } = useLocale();
  return (<><Head title={`${customer.customer_code} - ${t('print.customerLedger')}`} />
  <div className="min-h-screen bg-slate-100 px-4 py-6 text-slate-900 print:bg-white print:px-0 print:py-0"><div className="mx-auto max-w-6xl rounded-3xl bg-white p-6 shadow-sm print:max-w-none print:rounded-none print:p-8 print:shadow-none">
    <PrintActions backHref={backHref} downloadHref={pdfDownloadUrl} saveLabel={t('print.savePdf')} />
    <div className="border-b-2 border-slate-900 pb-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{organization?.name || t('common.appName')}</h1><p className="mt-1 text-sm text-slate-500">{organization?.address}</p></div><div className="text-right text-sm"><p className="inline-flex rounded-full border border-slate-300 px-3 py-1 text-xs font-semibold uppercase tracking-wide">{t('print.officialDocument')}</p><p className="mt-3 font-semibold">{customer.customer_code}</p><p className="text-slate-500">{meta?.generated_at}</p></div></div></div>
    <div className="mt-4 border-b border-slate-200 pb-4"><h2 className="text-xl font-bold">{t('print.customerLedger')}</h2><p className="mt-1 text-sm text-slate-500">{customer.name} · {customer.phone || '-'}</p></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[[t('customers.totalPayable'), customer.total_payable_money],[t('customers.totalPaid'), customer.total_paid_money],[t('customers.remainingBalance'), customer.remaining_balance_money],[t('customers.overdueAmount'), customer.overdue_amount_money]].map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>)}</div>
    <div className="mt-6 overflow-hidden rounded-2xl border border-slate-200"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-base font-semibold">{t('customers.loanInformation')}</h2></div><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{[t('loans.loanCode'), t('loans.status'), t('customers.totalPayable'), t('customers.totalPaid'), t('customers.remainingBalance'), t('customers.loanNextDue')].map((h)=><th key={h} className="px-4 py-3 text-left font-medium text-slate-500">{h}</th>)}</tr></thead><tbody>{customer.loans?.length ? customer.loans.map((loan)=><tr key={loan.loan_code} className="border-t border-slate-200"><td className="px-4 py-3">{loan.loan_code}</td><td className="px-4 py-3">{loan.status_label}</td><td className="px-4 py-3">{loan.total_payable_money}</td><td className="px-4 py-3">{loan.total_paid_money}</td><td className="px-4 py-3">{loan.remaining_balance_money}</td><td className="px-4 py-3">{loan.next_due_date} {loan.next_due_date ? `· ${loan.next_due_amount_money}` : ''}</td></tr>) : <tr><td colSpan="6" className="px-4 py-8 text-center text-slate-500">{t('loans.noLoans')}</td></tr>}</tbody></table></div>
    <div className="mt-6 overflow-hidden rounded-2xl border border-slate-200"><div className="border-b border-slate-200 px-4 py-3"><h2 className="text-base font-semibold">{t('customers.paymentHistory')}</h2></div><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{[t('payments.paymentCode'), t('payments.paymentDate'), t('payments.loan'), t('payments.amount'), t('payments.paymentMethod'), t('payments.paymentMode')].map((h)=><th key={h} className="px-4 py-3 text-left font-medium text-slate-500">{h}</th>)}</tr></thead><tbody>{customer.payments?.length ? customer.payments.map((payment)=><tr key={payment.payment_code} className="border-t border-slate-200"><td className="px-4 py-3">{payment.payment_code}</td><td className="px-4 py-3">{payment.payment_date}</td><td className="px-4 py-3">{payment.loan_code}</td><td className="px-4 py-3">{payment.amount_money}</td><td className="px-4 py-3">{payment.payment_method_label}</td><td className="px-4 py-3">{payment.payment_type_label}</td></tr>) : <tr><td colSpan="6" className="px-4 py-8 text-center text-slate-500">{t('payments.noPayments')}</td></tr>}</tbody></table></div>
  </div></div></>);
}
